name: 3 - Deploy Workflow Call

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  deploy_homolog:
    runs-on: ubuntu-latest
    environment:
      name: homolog
      url: https://tiagoboeing.com
    steps:
      - run: "Start"

      - name: Deploy Homolog
        if: inputs.environment == 'development'
        run: echo "Running deploy script to ${{ inputs.environment }} environment..."
