name: 3 - Deploy Workflow Call

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  deploy_homolog:
    if: inputs.environment == 'development'
    runs-on: ubuntu-latest
    environment:
      name: homolog
      url: https://tiagoboeing.com
    steps:
      - run: echo "Running deploy script to ${{ inputs.environment }} environment..."
