name: 4 - Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: "sandbox"
        options:
          - "sandbox"
          - "development"
          - "homolog"
          - "staging"

  # pull_request:
  #   types: [opened, reopened, synchronize, ready_for_review]
  # push:
  #   branches: [master]

defaults:
  run:
    shell: bash

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running deploy script..."
          echo "${{ toJSON(github) }}"
          echo "${{ toJSON(github.event) }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build_test
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment }}.tiagoboeing.com
    steps:
      - name: Deploy
        run: echo "Running deploy script to ${{ inputs.environment }} environment..."

  deploy_homolog:
    name: Check deploy to homolog
    needs: deploy
    environment:
      name: homolog
      url: https://tiagoboeing.com
    steps:
      # only if not a hotfix branch
      - name: Check deploy to homolog
        if: "!startsWith(github.ref, 'refs/heads/hotfix/') && inputs.environment == 'development' && needs.deploy.result == 'success'"
        run: echo "Checking deploy to homolog..."

  create_release:
    name: Requires review and create release to production
    # if: always()
    runs-on: ubuntu-latest
    needs: [deploy, deploy_homolog]
    environment:
      name: production
      url: https://tiagoboeing.com
    steps:
      - run: echo "Run release/tag/changelog script..."

  deploy_production:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - run: echo "Running deploy script to production environment..."

  merge_branches:
    runs-on: ubuntu-latest
    needs: deploy_production
    concurrency: 1
    steps:
      - run: echo "Merge to master and develop."

  sync_envs:
    runs-on: ubuntu-latest
    concurrency: 1
    needs: deploy_production
    steps:
      - run: echo "Sync environments."
