name: 6 - Deploy Snapshot

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: "sandbox"
        options:
          - "sandbox"
          - "development"
          - "homolog"
          - "staging"

defaults:
  run:
    shell: bash

jobs:
  download_actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running deploy script..."
          echo "${{ toJSON(github) }}"
          echo "${{ toJSON(github.event) }}"

  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: download_actions
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment }}.tiagoboeing.com
    steps:
      - run: echo "Running deploy script to ${{ inputs.environment }} environment..."
