name: 6 - Deploy Snapshot

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Ambiente de implantação
        type: choice
        default: "sandbox"
        required: true
        options:
          - "sandbox"
          - "development"
          - "homolog"

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment }}.tiagoboeing.com
    steps:
      - uses: actions/checkout@v2

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ${{ github.workspace }}/.github/config
          mode: ${{ inputs.environment }}

      - run: |
          echo "function_app_name = ${{ env.function_app_name }}"
