name: 6 - Deploy Snapshot

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Ambiente de implantação
        type: choice
        default: "sandbox"
        required: true
        options:
          - "sandbox"
          - "development"
          - "homolog"

defaults:
  run:
    shell: bash

jobs:
  download_actions:
    name: Configure Actions
    runs-on: ubuntu-latest
    steps:
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ${{ github.workspace }}/.github/config
          mode: ${{ inputs.environment }}

  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: download_actions
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment }}.tiagoboeing.com
    steps:
      - run: |
          echo "function_app_name = ${{ env.function_app_name }}"

      - name: Infra Terraform
        uses: ./.github/actions/terraform-azure-function-app
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          function_app_name: ${{ env.function_app_name }}
          resource_group_name: "nestjs-github-action"
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build project
        uses: ./.github/actions/azure-function-build-nodejs

      - name: Function Deploy
        uses: ./.github/actions/azure-function-deploy
        with:
          function_app_name: ${{ env.function_app_name }}
          install_az_cli: "true"
          function_runtime: "javascript"
