name: 6 - Release - Feature

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  download_actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running deploy script..."
          echo "${{ toJSON(github) }}"
          echo "${{ toJSON(github.event) }}"

  deploy_dev:
    name: Deploy Development
    runs-on: ubuntu-latest
    needs: download_actions
    environment:
      name: development
      url: https://dev-tiagoboeing.com
    steps:
      - run: echo "Running deploy script..."

  deploy_homolog:
    runs-on: ubuntu-latest
    needs: deploy_dev
    environment:
      name: homolog
      url: https://homolog-tiagoboeing.com
    steps:
      - run: echo "Running deploy script to homolog environment..."

  create_release:
    runs-on: ubuntu-latest
    needs: deploy_homolog
    environment:
      name: production
      url: https://tiagoboeing.com
    steps:
      - run: echo "Run release/tag/changelog script..."

  deploy_production:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - run: echo "Running deploy script to production environment..."

  merge_branches:
    runs-on: ubuntu-latest
    needs: deploy_production
    steps:
      - run: echo "Merge to master and develop."

  sync_envs:
    runs-on: ubuntu-latest
    needs: merge_branches
    steps:
      - run: echo "Sync environments."
