name: 6 - Start release

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  configure:
    name: Configure Workflow
    if: "!startsWith(github.ref, 'refs/heads/hotfix/')"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "DEFAULT BRANCH = ${{ github.event.repository.default_branch }}"
          echo "DEFAULT BRANCH2 = refs/heads/${{ github.event.repository.default_branch }}"
          echo "Running deploy script..."
          echo "${{ toJSON(github) }}"
          echo "${{ toJSON(github.event) }}"

  # runs only if not develop branch
  deploy_dev:
    name: Deploy to development
    if: github.ref != "refs/heads/develop" && github.ref != "refs/heads/${{ github.event.repository.default_branch }}"
    runs-on: ubuntu-latest
    needs: configure
    environment:
      name: development
      url: https://dev-tiagoboeing.com
    steps:
      - uses: actions/checkout@v2

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ${{ github.workspace }}/.github/config
          mode: development

      - run: |
          echo "function_app_name = ${{ env.function_app_name }}"

  deploy_homolog:
    name: Deploy to homolog
    runs-on: ubuntu-latest
    needs: deploy_dev
    environment:
      name: homolog
      url: https://homolog-tiagoboeing.com
    steps:
      - uses: actions/checkout@v2

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ${{ github.workspace }}/.github/config
          mode: homolog

      - run: |
          echo "function_app_name = ${{ env.function_app_name }}"

  create_release:
    runs-on: ubuntu-latest
    needs: deploy_homolog
    environment:
      name: production
      url: https://tiagoboeing.com
    steps:
      - run: echo "Run release/tag/changelog script..."

  deploy_production:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v2

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ${{ github.workspace }}/.github/config
          mode: production

      - run: |
          echo "function_app_name = ${{ env.function_app_name }}"

  merge_branches:
    runs-on: ubuntu-latest
    needs: deploy_production
    steps:
      - run: echo "Merge to master and develop."

  sync_envs:
    runs-on: ubuntu-latest
    needs: merge_branches
    steps:
      - run: echo "Sync environments."
