name: Build and deploy

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build code
        run: echo "Build code"

      - name: Run tests
        run: "echo Run unit tests"

  deploy_dev:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

