name: Build and deploy

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - "!master"
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build code
        run: echo "Build code"

      - name: Run tests
        run: "echo Run unit tests"

      - run: |
          echo "Running deploy script..."
          echo "${{ toJSON(github) }}"
          echo "${{ toJSON(github.event) }}"

  deploy_dev:
    needs: build_test
    if: ${{ github.ref_name == 'master' }}
    environment:
      name: dev
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy script..."

  deploy_sandbox:
    needs: build_test
    if: ${{ github.event.pull_request.base.ref == 'master' }}
    environment:
      name: sandbox
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy script..."

  deploy_hlg:
    needs: deploy_dev
    if: ${{ github.ref_name == 'master' }}
    environment:
      name: hlg
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy script..."

  deploy_prod:
    needs: deploy_hlg
    if: ${{ github.ref_name == 'master' }}
    environment:
      name: prod
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy script..."

  deploy_stg:
    needs: deploy_hlg
    concurrency: deploy_prod
    environment:
      name: stg
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy script..."
