name: Build and deploy

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build code
        run: echo "Build code"

      - name: Run tests
        run: "echo Run unit tests"

  deploy_dev:
    needs: build_test
    environment:
      name: dev
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "Running deploy script..."

  deploy_hlg:
    needs: deploy_dev
    environment:
      name: hlg
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "Running deploy script..."

  deploy_prd:
    needs: deploy_hlg
    environment:
      name: prod
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "Running deploy script..."
