name: Build and deploy

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: [master]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build code
        run: echo "Build code"

      - name: Run tests
        run: "echo Run unit tests"

      - run: |
          echo "Running deploy script..."
          echo "${{ toJSON(github) }}"
          echo "${{ toJSON(github.event) }}"

  deploy_dev:
    needs: build_test
    if: github.ref_name == 'master'
    environment:
      name: development
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy script..."

  deploy_sandbox:
    needs: build_test
    if: github.event.pull_request.base.ref == 'master'
    environment:
      name: sandbox
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy script..."

  deploy_hlg:
    needs: deploy_dev
    if: github.ref_name == 'master'
    environment:
      name: homolog
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy script..."

  deploy_stg:
    needs: deploy_dev
    concurrency: deploy_dev
    environment:
      name: staging
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy script..."

  deploy_prod:
    needs: deploy_hlg
    if: github.ref_name == 'master'
    environment:
      name: production
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy script..."
