name: Deploy to environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: "sandbox"
        options:
          - "sandbox"
          - "development"
          - "homolog"
          - "staging"

  # pull_request:
  #   types: [opened, reopened, synchronize, ready_for_review]
  # push:
  #   branches: [master]

defaults:
  run:
    shell: bash

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build code
        run: echo "Build code"

      - name: Run tests
        run: "echo Run unit tests"

      - run: |
          echo "Running deploy script..."
          echo "${{ toJSON(github) }}"
          echo "${{ toJSON(github.event) }}"

  deploy_snapshot:
    runs-on: ubuntu-latest
    needs: build_test
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment }}.tiagoboeing.com
    steps:
      - run: echo "Running deploy script to ${{ inputs.environment }} environment..."

  # Deploy and start test flow
  deploy_homolog:
    runs-on: ubuntu-latest
    needs: deploy_snapshot
    environment:
      name: homolog
      url: https://tiagoboeing.com
    steps:
      - run: echo "Running deploy script to ${{ inputs.environment }} environment..."

  create_release:
    runs-on: ubuntu-latest
    needs: deploy_homolog
    environment:
      name: production
      url: https://tiagoboeing.com
    steps:
      - run: echo "Run release/tag/changelog script..."

  deploy_production:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - run: echo "Running deploy script to production environment..."

  merge_branches:
    runs-on: ubuntu-latest
    needs: deploy_production
    steps:
      - run: echo "Merge to master and develop."

  sync_envs:
    runs-on: ubuntu-latest
    needs: deploy_production
    steps:
      - run: echo "Sync environments."
