name: Single Manual Environment Workflow

on:
  # pull_request:
  #   types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment to deploy
        required: true

      create_version:
        type: boolean
        default: false

      version_type:
        type: choice
        default: "patch"
        options:
          - "patch"
          - "minor"
          - "major"

defaults:
  run:
    shell: bash

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build code
        run: echo "Build code"

      - name: Run tests
        run: echo "Run unit tests"

      - run: |
          echo "Running deploy script..."
          echo "${{ inputs.environment }}"

  create_version:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Create version = ${{ inputs.create_version }}"
          echo "Version type = ${{ inputs.version_type }}"

  deploy:
    needs: create_version
    # if: github.ref_name == 'master'
    environment:
      name: ${{ inputs.environment }}
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy script..."

  deploy_sandbox:
    needs: build_test
    if: github.event.pull_request.base.ref == 'master'
    environment:
      name: sandbox
      url: https://tiagoboeing.com
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy script..."
